apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spin
resources:
  - external-secret.yaml
images:
  - name: spin-transactions
    newName: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/spin-transactions
    newTag: latest